const MenuItems = [
  // ============================
  // Gujarati Cuisine
  // ============================
  { name: 'Dhokla', description: 'Steamed gram flour snack', price: 2.99, image_url: 'https://source.unsplash.com/featured/?dhokla', cuisine: 'gujarati', isActive: true },
  { name: 'Khandvi', description: 'Rolled gram flour snack with spices', price: 3.49, image_url: 'https://source.unsplash.com/featured/?khandvi', cuisine: 'gujarati', isActive: true },
  { name: 'Undhiyu', description: 'Mixed vegetable curry', price: 10.99, image_url: 'https://source.unsplash.com/featured/?undhiyu', cuisine: 'gujarati', isActive: true },
  { name: 'Thepla', description: 'Spiced flatbread', price: 4.49, image_url: 'https://source.unsplash.com/featured/?thepla', cuisine: 'gujarati', isActive: true },
  { name: 'Fafda', description: 'Crispy gram flour snack', price: 2.99, image_url: 'https://source.unsplash.com/featured/?fafda', cuisine: 'gujarati', isActive: true },
  { name: 'Handvo', description: 'Savory vegetable cake', price: 5.49, image_url: 'https://source.unsplash.com/featured/?handvo', cuisine: 'gujarati', isActive: true },
  { name: 'Khakhra', description: 'Thin crispy flatbread', price: 2.49, image_url: 'https://source.unsplash.com/featured/?khakhra', cuisine: 'gujarati', isActive: true },
  { name: 'Patra', description: 'Steamed colocasia leaves rolls', price: 3.99, image_url: 'https://source.unsplash.com/featured/?patra,indian-food', cuisine: 'gujarati', isActive: true },
  { name: 'Sev Khamani', description: 'Mashed gram snack topped with sev', price: 3.99, image_url: 'https://source.unsplash.com/featured/?sev,indian-snack', cuisine: 'gujarati', isActive: true },
  { name: 'Dal Dhokli', description: 'Lentil soup with wheat dumplings', price: 6.99, image_url: 'https://source.unsplash.com/featured/?dal,indian-curry', cuisine: 'gujarati', isActive: true },
  { name: 'Muthiya', description: 'Steamed gram flour dumplings', price: 4.99, image_url: 'https://source.unsplash.com/featured/?muthiya', cuisine: 'gujarati', isActive: true },
  { name: 'Puran Poli', description: 'Sweet stuffed flatbread', price: 5.49, image_url: 'https://source.unsplash.com/featured/?puran-poli', cuisine: 'gujarati', isActive: true },
  { name: 'Shrikhand', description: 'Sweetened yogurt dessert', price: 3.99, image_url: 'https://source.unsplash.com/featured/?shrikhand', cuisine: 'gujarati', isActive: true },
  { name: 'Masala Chai', description: 'Spiced tea', price: 2.49, image_url: 'https://source.unsplash.com/featured/?masala-chai', cuisine: 'gujarati', isActive: true },
  { name: 'Badam Milk', description: 'Almond-flavored milk drink', price: 3.49, image_url: 'https://source.unsplash.com/featured/?badam-milk', cuisine: 'gujarati', isActive: true },
  { name: 'Sol Kadhi', description: 'Coconut and kokum drink', price: 2.99, image_url: 'https://source.unsplash.com/featured/?sol-kadhi', cuisine: 'gujarati', isActive: true },
  { name: 'Kesar Peda', description: 'Sweet milk fudge with saffron', price: 2.99, image_url: 'https://source.unsplash.com/featured/?peda,indian-sweet', cuisine: 'gujarati', isActive: true },
  { name: 'Batata Vada', description: 'Fried potato dumplings', price: 3.49, image_url: 'https://source.unsplash.com/featured/?batata-vada', cuisine: 'gujarati', isActive: true },
  { name: 'Bhajiya', description: 'Spiced vegetable fritters', price: 3.49, image_url: 'https://source.unsplash.com/featured/?pakora', cuisine: 'gujarati', isActive: true },
  { name: 'Gujarati Kadhi', description: 'Tangy yogurt-based curry', price: 4.99, image_url: 'https://source.unsplash.com/featured/?kadhi', cuisine: 'gujarati', isActive: true },
  { name: 'Ringan No Olo', description: 'Mashed eggplant with spices', price: 5.49, image_url: 'https://source.unsplash.com/featured/?baingan-bharta', cuisine: 'gujarati', isActive: true },
  { name: 'Sev Tameta', description: 'Tomato curry topped with sev', price: 4.99, image_url: 'https://source.unsplash.com/featured/?tomato-curry', cuisine: 'gujarati', isActive: true },
  { name: 'Khichu', description: 'Spiced rice flour snack', price: 3.49, image_url: 'https://source.unsplash.com/featured/?khichu', cuisine: 'gujarati', isActive: true },
  { name: 'Lapsi', description: 'Sweet broken wheat pudding', price: 3.99, image_url: 'https://source.unsplash.com/featured/?lapsi,indian-dessert', cuisine: 'gujarati', isActive: true },
  { name: 'Khaman', description: 'Soft gram flour cake', price: 3.49, image_url: 'https://source.unsplash.com/featured/?khaman', cuisine: 'gujarati', isActive: true },
  { name: 'Rasgulla', description: 'Soft cheese ball dessert', price: 2.99, image_url: 'https://source.unsplash.com/featured/?rasgulla', cuisine: 'gujarati', isActive: true },
  { name: 'Mango Lassi', description: 'Sweet mango yogurt drink', price: 3.99, image_url: 'https://source.unsplash.com/featured/?mango-lassi', cuisine: 'gujarati', isActive: true },
  { name: 'Vegetable Handvo', description: 'Savory vegetable cake', price: 5.49, image_url: 'https://source.unsplash.com/featured/?handvo,vegetable', cuisine: 'gujarati', isActive: true },
  { name: 'Khichdi', description: 'Lentils and rice porridge', price: 5.99, image_url: 'https://source.unsplash.com/featured/?khichdi', cuisine: 'gujarati', isActive: true },
  { name: 'Paneer Patrani', description: 'Paneer steamed in banana leaf with chutney', price: 11.99, image_url: 'https://source.unsplash.com/featured/?paneer,banana-leaf', cuisine: 'gujarati', isActive: true },
  { name: 'Vegetable Farsan Platter', description: 'Mixed Gujarati snacks', price: 7.99, image_url: 'https://source.unsplash.com/featured/?indian-thali', cuisine: 'gujarati', isActive: true },
  { name: 'Dal Fry', description: 'Cooked lentils with spices', price: 6.49, image_url: 'https://source.unsplash.com/featured/?dal-fry', cuisine: 'gujarati', isActive: true },
  { name: 'Kadhi Fafda', description: 'Gujarati kadhi served with fafda', price: 7.49, image_url: 'https://source.unsplash.com/featured/?fafda,kadhi', cuisine: 'gujarati', isActive: true },
  { name: 'Sweet Ladoo', description: 'Traditional sweet balls', price: 2.99, image_url: 'https://source.unsplash.com/featured/?ladoos', cuisine: 'gujarati', isActive: true },
  { name: 'Basundi', description: 'Thickened sweetened milk', price: 4.99, image_url: 'https://source.unsplash.com/featured/?basundi', cuisine: 'gujarati', isActive: true },

  // ============================
  // Punjabi Cuisine (Vegetarian)
  // ============================
  { name: 'Paneer Butter Masala', description: 'Paneer in rich creamy tomato gravy', price: 12.49, image_url: 'https://source.unsplash.com/featured/?paneer-butter-masala', cuisine: 'punjabi', isActive: true },
  { name: 'Dal Makhani', description: 'Slow-cooked black lentils with cream', price: 9.99, image_url: 'https://source.unsplash.com/featured/?dal-makhani', cuisine: 'punjabi', isActive: true },
  { name: 'Paneer Tikka', description: 'Marinated cottage cheese grilled in tandoor', price: 8.49, image_url: 'https://source.unsplash.com/featured/?paneer-tikka', cuisine: 'punjabi', isActive: true },
  { name: 'Sarson Da Saag', description: 'Mustard greens with spices', price: 8.99, image_url: 'https://source.unsplash.com/featured/?sarson-da-saag', cuisine: 'punjabi', isActive: true },
  { name: 'Makki Di Roti', description: 'Maize flour flatbread', price: 2.49, image_url: 'https://source.unsplash.com/featured/?makki-di-roti', cuisine: 'punjabi', isActive: true },
  { name: 'Chole Bhature', description: 'Spicy chickpeas with fried bread', price: 7.99, image_url: 'https://source.unsplash.com/featured/?chole-bhature', cuisine: 'punjabi', isActive: true },
  { name: 'Amritsari Kulcha', description: 'Stuffed bread from Amritsar', price: 4.99, image_url: 'https://source.unsplash.com/featured/?amritsari-kulcha', cuisine: 'punjabi', isActive: true },
  { name: 'Rajma Chawal', description: 'Red kidney beans with steamed rice', price: 6.99, image_url: 'https://source.unsplash.com/featured/?rajma-chawal', cuisine: 'punjabi', isActive: true },
  { name: 'Kadai Paneer', description: 'Paneer cooked with bell peppers and spices', price: 10.49, image_url: 'https://source.unsplash.com/featured/?kadai-paneer', cuisine: 'punjabi', isActive: true },
  { name: 'Aloo Paratha', description: 'Potato-stuffed flatbread', price: 3.99, image_url: 'https://source.unsplash.com/featured/?aloo-paratha', cuisine: 'punjabi', isActive: true },
  { name: 'Veg Biryani', description: 'Fragrant basmati rice with vegetables', price: 12.99, image_url: 'https://source.unsplash.com/featured/?veg-biryani', cuisine: 'punjabi', isActive: true },
  { name: 'Malai Kofta', description: 'Vegetable balls in creamy gravy', price: 11.49, image_url: 'https://source.unsplash.com/featured/?malai-kofta', cuisine: 'punjabi', isActive: true },
  { name: 'Baingan Bharta', description: 'Roasted mashed eggplant', price: 8.99, image_url: 'https://source.unsplash.com/featured/?baingan-bharta', cuisine: 'punjabi', isActive: true },
  { name: 'Shahi Paneer', description: 'Paneer in royal creamy gravy', price: 11.49, image_url: 'https://source.unsplash.com/featured/?shahi-paneer', cuisine: 'punjabi', isActive: true },
  { name: 'Jeera Rice', description: 'Cumin-tempered basmati rice', price: 4.99, image_url: 'https://source.unsplash.com/featured/?jeera-rice', cuisine: 'punjabi', isActive: true },
  { name: 'Garlic Naan', description: 'Leavened bread with garlic', price: 2.99, image_url: 'https://source.unsplash.com/featured/?garlic-naan', cuisine: 'punjabi', isActive: true },
  { name: 'Missi Roti', description: 'Gram flour flatbread', price: 2.49, image_url: 'https://source.unsplash.com/featured/?missi-roti', cuisine: 'punjabi', isActive: true },
  { name: 'Gulab Jamun', description: 'Deep-fried milk dumplings in syrup', price: 3.49, image_url: 'https://source.unsplash.com/featured/?gulab-jamun', cuisine: 'punjabi', isActive: true },
  { name: 'Paneer Bhurji', description: 'Scrambled cottage cheese', price: 9.49, image_url: 'https://source.unsplash.com/featured/?paneer-bhurji', cuisine: 'punjabi', isActive: true },
  { name: 'Dahi Bhalla', description: 'Lentil dumplings in yogurt', price: 4.99, image_url: 'https://source.unsplash.com/featured/?dahi-bhalla', cuisine: 'punjabi', isActive: true },

  // ============================
  // Continental (Vegetarian)
  // ============================
  { name: 'Margherita Pizza', description: 'Classic tomato and mozzarella pizza', price: 11.99, image_url: 'https://source.unsplash.com/featured/?margherita-pizza', cuisine: 'continental', isActive: true },
  { name: 'Penne Alfredo', description: 'Pasta in creamy white sauce', price: 10.49, image_url: 'https://source.unsplash.com/featured/?penne-alfredo', cuisine: 'continental', isActive: true },
  { name: 'Veg Burger', description: 'Vegetable patty with lettuce and cheese', price: 11.49, image_url: 'https://source.unsplash.com/featured/?veg-burger', cuisine: 'continental', isActive: true },
  { name: 'Vegetable Lasagna', description: 'Layered pasta with veggies and cheese', price: 12.49, image_url: 'https://source.unsplash.com/featured/?vegetable-lasagna', cuisine: 'continental', isActive: true },
  { name: 'Spaghetti Aglio e Olio', description: 'Pasta with garlic and olive oil', price: 9.99, image_url: 'https://source.unsplash.com/featured/?spaghetti-aglio-e-olio', cuisine: 'continental', isActive: true },
  { name: 'Mushroom Risotto', description: 'Creamy Italian rice with mushrooms', price: 11.99, image_url: 'https://source.unsplash.com/featured/?mushroom-risotto', cuisine: 'continental', isActive: true },
  { name: 'French Fries', description: 'Crispy deep-fried potato strips', price: 3.99, image_url: 'https://source.unsplash.com/featured/?french-fries', cuisine: 'continental', isActive: true },
  { name: 'Macaroni and Cheese', description: 'Pasta in rich cheddar sauce', price: 9.49, image_url: 'https://source.unsplash.com/featured/?mac-and-cheese', cuisine: 'continental', isActive: true },
  { name: 'Veg Au Gratin', description: 'Baked vegetables in white sauce', price: 10.99, image_url: 'https://source.unsplash.com/featured/?au-gratin', cuisine: 'continental', isActive: true },
  { name: 'Tiramisu', description: 'Coffee-flavored Italian dessert', price: 6.99, image_url: 'https://source.unsplash.com/featured/?tiramisu', cuisine: 'continental', isActive: true },
  { name: 'Chocolate Fondant', description: 'Molten chocolate cake', price: 6.49, image_url: 'https://source.unsplash.com/featured/?chocolate-fondant', cuisine: 'continental', isActive: true },
];

export default MenuItems;
