const MenuItems = [
  // ============================
  // Gujarati Cuisine (35 items)
  // ============================
  { name: 'Dhokla', description: 'Steamed gram flour snack', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Khandvi', description: 'Rolled gram flour snack with spices', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Undhiyu', description: 'Mixed vegetable curry', price: 10.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Thepla', description: 'Spiced flatbread', price: 4.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Fafda', description: 'Crispy gram flour snack', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Handvo', description: 'Savory vegetable cake', price: 5.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Khakhra', description: 'Thin crispy flatbread', price: 2.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Patra', description: 'Steamed colocasia leaves rolls', price: 3.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Sev Khamani', description: 'Mashed gram snack topped with sev', price: 3.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Dal Dhokli', description: 'Lentil soup with wheat dumplings', price: 6.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Muthiya', description: 'Steamed gram flour dumplings', price: 4.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Puran Poli', description: 'Sweet stuffed flatbread', price: 5.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Shrikhand', description: 'Sweetened yogurt dessert', price: 3.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Masala Chai', description: 'Spiced tea', price: 2.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Badam Milk', description: 'Almond-flavored milk drink', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Sol Kadhi', description: 'Coconut and kokum drink', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Kesar Peda', description: 'Sweet milk fudge with saffron', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Batata Vada', description: 'Fried potato dumplings', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Bhajiya', description: 'Spiced vegetable fritters', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Gujarati Kadhi', description: 'Tangy yogurt-based curry', price: 4.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Ringan No Olo', description: 'Mashed eggplant with spices', price: 5.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Sev Tameta', description: 'Tomato curry topped with sev', price: 4.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Khichu', description: 'Spiced rice flour snack', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Lapsi', description: 'Sweet broken wheat pudding', price: 3.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Khaman', description: 'Soft gram flour cake', price: 3.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Rasgulla', description: 'Soft cheese ball dessert', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Mango Lassi', description: 'Sweet mango yogurt drink', price: 3.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Vegetable Handvo', description: 'Savory vegetable cake', price: 5.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Khichdi', description: 'Lentils and rice porridge', price: 5.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Patrani Machhi', description: 'Fish steamed in banana leaf', price: 12.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Vegetable Farsan Platter', description: 'Mixed Gujarati snacks', price: 7.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Dal Fry', description: 'Cooked lentils with spices', price: 6.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Kadhi Fafda', description: 'Gujarati kadhi served with fafda', price: 7.49, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Sweet Ladoo', description: 'Traditional sweet balls', price: 2.99, image_url: '', cuisine: 'gujarati', isActive: true },
  { name: 'Basundi', description: 'Thickened sweetened milk', price: 4.99, image_url: '', cuisine: 'gujarati', isActive: true },

  // ============================
  // Punjabi Cuisine (35 items)
  // ============================
  { name: 'Butter Chicken', description: 'Tender chicken in creamy tomato sauce', price: 12.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Dal Makhani', description: 'Slow-cooked black lentils with cream', price: 9.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Paneer Tikka', description: 'Marinated cottage cheese grilled in tandoor', price: 8.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Sarson Da Saag', description: 'Mustard greens with spices', price: 8.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Makki Di Roti', description: 'Maize flour flatbread', price: 2.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Chole Bhature', description: 'Spicy chickpeas with fried bread', price: 7.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Amritsari Kulcha', description: 'Stuffed bread from Amritsar', price: 4.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Rajma Chawal', description: 'Red kidney beans with steamed rice', price: 6.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Kadai Paneer', description: 'Paneer cooked with bell peppers and spices', price: 10.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Tandoori Chicken', description: 'Roasted chicken marinated in yogurt and spices', price: 11.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Aloo Paratha', description: 'Potato-stuffed flatbread', price: 3.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Lassi (Sweet)', description: 'Thick churned yogurt drink', price: 3.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Malai Kofta', description: 'Vegetable balls in creamy gravy', price: 11.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Baingan Bharta', description: 'Roasted mashed eggplant', price: 8.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Chicken Tikka Masala', description: 'Grilled chicken in spiced curry', price: 12.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Gajar Ka Halwa', description: 'Sweet carrot pudding', price: 4.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Pindi Chole', description: 'Dry spicy chickpeas', price: 7.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Mutton Rogan Josh', description: 'Traditional lamb curry', price: 14.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Paneer Lababdar', description: 'Cottage cheese in rich tomato gravy', price: 11.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Bhutte Ka Kees', description: 'Grated corn cooked with spices', price: 5.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Jeera Rice', description: 'Cumin-tempered basmati rice', price: 4.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Garlic Naan', description: 'Leavened bread with garlic', price: 2.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Missi Roti', description: 'Gram flour flatbread', price: 2.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Chicken Biryani', description: 'Spiced chicken and rice', price: 13.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Veg Pulao', description: 'Fragrant rice with vegetables', price: 7.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Gulab Jamun', description: 'Deep-fried milk dumplings in syrup', price: 3.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Shahi Paneer', description: 'Paneer in royal creamy gravy', price: 11.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Tandoori Roti', description: 'Whole wheat bread from clay oven', price: 1.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Mixed Veg Pakoda', description: 'Assorted vegetable fritters', price: 5.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Paneer Bhurji', description: 'Scrambled cottage cheese', price: 9.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Dahi Bhalla', description: 'Lentil dumplings in yogurt', price: 4.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Fish Tikka', description: 'Grilled marinated fish chunks', price: 13.99, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Moong Dal Halwa', description: 'Yellow lentil sweet pudding', price: 5.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Kadai Chicken', description: 'Chicken cooked in a wok with spices', price: 12.49, image_url: '', cuisine: 'punjabi', isActive: true },
  { name: 'Amritsari Machhi', description: 'Deep-fried fish fillets with spices', price: 14.49, image_url: '', cuisine: 'punjabi', isActive: true },

  // ============================
  // Continental Cuisine (30 items)
  // ============================
  { name: 'Margherita Pizza', description: 'Classic tomato and mozzarella pizza', price: 11.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Penne Alfredo', description: 'Pasta in creamy white sauce', price: 10.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Grilled Chicken Steak', description: 'Chicken breast with pepper sauce', price: 15.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Caesar Salad', description: 'Romaine lettuce with Caesar dressing', price: 8.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Fish and Chips', description: 'Battered fish with potato fries', price: 13.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Vegetable Lasagna', description: 'Layered pasta with veggies and cheese', price: 12.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Spaghetti Aglio e Olio', description: 'Pasta with garlic and olive oil', price: 9.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Mushroom Risotto', description: 'Creamy Italian rice with mushrooms', price: 11.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Chicken Piccata', description: 'Pan-seared chicken with lemon and capers', price: 14.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Garlic Bread with Cheese', description: 'Toasted bread with garlic and mozzarella', price: 4.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Bruschetta', description: 'Toasted bread topped with tomatoes', price: 6.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Veg Au Gratin', description: 'Baked vegetables in white sauce', price: 10.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Beef Burger', description: 'Classic patty with lettuce and cheese', price: 12.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Minestrone Soup', description: 'Traditional Italian vegetable soup', price: 5.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Tiramisu', description: 'Coffee-flavored Italian dessert', price: 6.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: "Shepherd's Pie", description: 'Minced meat topped with mashed potatoes', price: 13.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Ratatouille', description: 'Stewed Mediterranean vegetables', price: 9.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Loaded Nachos', description: 'Tortilla chips with cheese and salsa', price: 8.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Chicken Cordon Bleu', description: 'Chicken wrapped around ham and cheese', price: 16.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Greek Salad', description: 'Cucumbers, olives, and feta cheese', price: 8.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'French Fries', description: 'Crispy deep-fried potato strips', price: 3.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Macaroni and Cheese', description: 'Pasta in rich cheddar sauce', price: 9.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Grilled Salmon', description: 'Salmon fillet with herbs and lemon', price: 18.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Quattro Formaggi Pizza', description: 'Four-cheese Italian pizza', price: 13.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Calamari Rings', description: 'Fried squid with dipping sauce', price: 11.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Beef Steak', description: 'Premium cut served with mashed potatoes', price: 22.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Spicy Arrabbiata Pasta', description: 'Pasta in spicy tomato sauce', price: 10.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Clam Chowder', description: 'Creamy soup with clams and vegetables', price: 7.99, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Chocolate Fondant', description: 'Molten chocolate cake', price: 6.49, image_url: '', cuisine: 'continental', isActive: true },
  { name: 'Caprese Salad', description: 'Tomato, mozzarella, basil', price: 7.49, image_url: '', cuisine: 'continental', isActive: true },
];

export default MenuItems;